# Generated by Django 5.0.6 on 2024-06-24 20:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("updownfunks", "0002_file_folder"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="folder",
            name="files",
        ),
        migrations.AlterField(
            model_name="file",
            name="folder",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="files",
                to="updownfunks.folder",
            ),
        ),
    ]
